/**
 * PingOne Platform API - Authorize
 * The PingOne Platform API covering the PingOne Authorize service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiAuthorize);
  }
}(this, function(expect, PingOnePlatformApiAuthorize) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiAuthorize.APIServer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIServer', function() {
    it('should create an instance of APIServer', function() {
      // uncomment below and update the code to test APIServer
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be.a(PingOnePlatformApiAuthorize.APIServer);
    });

    it('should have the property links (base name: "_links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

    it('should have the property authorizationServer (base name: "authorizationServer")', function() {
      // uncomment below and update the code to test the property authorizationServer
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

    it('should have the property baseURLs (base name: "baseURLs")', function() {
      // uncomment below and update the code to test the property baseURLs
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

    it('should have the property operations (base name: "operations")', function() {
      // uncomment below and update the code to test the property operations
      //var instance = new PingOnePlatformApiAuthorize.APIServer();
      //expect(instance).to.be();
    });

  });

}));
