/**
 * PingOne Platform API - Authorize
 * The PingOne Platform API covering the PingOne Authorize service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiAuthorize);
  }
}(this, function(expect, PingOnePlatformApiAuthorize) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DecisionEndpoint', function() {
    it('should create an instance of DecisionEndpoint', function() {
      // uncomment below and update the code to test DecisionEndpoint
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be.a(PingOnePlatformApiAuthorize.DecisionEndpoint);
    });

    it('should have the property links (base name: "_links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property alternateId (base name: "alternateId")', function() {
      // uncomment below and update the code to test the property alternateId
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property authorizationVersion (base name: "authorizationVersion")', function() {
      // uncomment below and update the code to test the property authorizationVersion
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property owned (base name: "owned")', function() {
      // uncomment below and update the code to test the property owned
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property policyId (base name: "policyId")', function() {
      // uncomment below and update the code to test the property policyId
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property provenance (base name: "provenance")', function() {
      // uncomment below and update the code to test the property provenance
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property recentDecisionsEnabled (base name: "recentDecisionsEnabled")', function() {
      // uncomment below and update the code to test the property recentDecisionsEnabled
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property recentDecisions (base name: "recentDecisions")', function() {
      // uncomment below and update the code to test the property recentDecisions
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

    it('should have the property recordRecentRequests (base name: "recordRecentRequests")', function() {
      // uncomment below and update the code to test the property recordRecentRequests
      //var instance = new PingOnePlatformApiAuthorize.DecisionEndpoint();
      //expect(instance).to.be();
    });

  });

}));
