/**
 * PingOne Platform API - PingOne Verify
 * The PingOne Platform API covering the PingOne Verify service
 *
 * The version of the OpenAPI document: 2023-07-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnumTimeUnit from './EnumTimeUnit';

/**
 * The TransactionConfigurationTimeout model module.
 * @module model/TransactionConfigurationTimeout
 * @version 2023-07-20
 */
class TransactionConfigurationTimeout {
    /**
     * Constructs a new <code>TransactionConfigurationTimeout</code>.
     * @alias module:model/TransactionConfigurationTimeout
     * @param duration {Number} Length of time before transaction timeout expires; range is 0-30 minutes or 0-1800 seconds.
     * @param timeUnit {module:model/EnumTimeUnit} 
     */
    constructor(duration, timeUnit) { 
        
        TransactionConfigurationTimeout.initialize(this, duration, timeUnit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, duration, timeUnit) { 
        obj['duration'] = duration;
        obj['timeUnit'] = timeUnit;
    }

    /**
     * Constructs a <code>TransactionConfigurationTimeout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionConfigurationTimeout} obj Optional instance to populate.
     * @return {module:model/TransactionConfigurationTimeout} The populated <code>TransactionConfigurationTimeout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionConfigurationTimeout();

            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('timeUnit')) {
                obj['timeUnit'] = EnumTimeUnit.constructFromObject(data['timeUnit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionConfigurationTimeout</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionConfigurationTimeout</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransactionConfigurationTimeout.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TransactionConfigurationTimeout.RequiredProperties = ["duration", "timeUnit"];

/**
 * Length of time before transaction timeout expires; range is 0-30 minutes or 0-1800 seconds.
 * @member {Number} duration
 */
TransactionConfigurationTimeout.prototype['duration'] = undefined;

/**
 * @member {module:model/EnumTimeUnit} timeUnit
 */
TransactionConfigurationTimeout.prototype['timeUnit'] = undefined;






export default TransactionConfigurationTimeout;

