/**
 * PingOne Platform API - PingOne Verify
 * The PingOne Platform API covering the PingOne Verify service
 *
 * The version of the OpenAPI document: 2023-07-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionConfigurationDataCollection from './TransactionConfigurationDataCollection';
import TransactionConfigurationTimeout from './TransactionConfigurationTimeout';

/**
 * The TransactionConfiguration model module.
 * @module model/TransactionConfiguration
 * @version 2023-07-20
 */
class TransactionConfiguration {
    /**
     * Constructs a new <code>TransactionConfiguration</code>.
     * @alias module:model/TransactionConfiguration
     */
    constructor() { 
        
        TransactionConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionConfiguration} obj Optional instance to populate.
     * @return {module:model/TransactionConfiguration} The populated <code>TransactionConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionConfiguration();

            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = TransactionConfigurationTimeout.constructFromObject(data['timeout']);
            }
            if (data.hasOwnProperty('dataCollection')) {
                obj['dataCollection'] = TransactionConfigurationDataCollection.constructFromObject(data['dataCollection']);
            }
            if (data.hasOwnProperty('dataCollectionOnly')) {
                obj['dataCollectionOnly'] = ApiClient.convertToType(data['dataCollectionOnly'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionConfiguration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionConfiguration</code>.
     */
    static validateJSON(data) {
        // validate the optional field `timeout`
        if (data['timeout']) { // data not null
          TransactionConfigurationTimeout.validateJSON(data['timeout']);
        }
        // validate the optional field `dataCollection`
        if (data['dataCollection']) { // data not null
          TransactionConfigurationDataCollection.validateJSON(data['dataCollection']);
        }

        return true;
    }


}



/**
 * @member {module:model/TransactionConfigurationTimeout} timeout
 */
TransactionConfiguration.prototype['timeout'] = undefined;

/**
 * @member {module:model/TransactionConfigurationDataCollection} dataCollection
 */
TransactionConfiguration.prototype['dataCollection'] = undefined;

/**
 * @member {Boolean} dataCollectionOnly
 */
TransactionConfiguration.prototype['dataCollectionOnly'] = undefined;






export default TransactionConfiguration;

