/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertChannel', function() {
    it('should create an instance of AlertChannel', function() {
      // uncomment below and update the code to test AlertChannel
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.AlertChannel);
    });

    it('should have the property links (base name: "_links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property environment (base name: "environment")', function() {
      // uncomment below and update the code to test the property environment
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property channelType (base name: "channelType")', function() {
      // uncomment below and update the code to test the property channelType
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property includeSeverities (base name: "includeSeverities")', function() {
      // uncomment below and update the code to test the property includeSeverities
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property includeAlertTypes (base name: "includeAlertTypes")', function() {
      // uncomment below and update the code to test the property includeAlertTypes
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

    it('should have the property excludeAlertTypes (base name: "excludeAlertTypes")', function() {
      // uncomment below and update the code to test the property excludeAlertTypes
      //var instance = new PingOnePlatformApiSsoAndBase.AlertChannel();
      //expect(instance).to.be();
    });

  });

}));
