/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FormFieldSocialLoginButton', function() {
    it('should create an instance of FormFieldSocialLoginButton', function() {
      // uncomment below and update the code to test FormFieldSocialLoginButton
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property styles (base name: "styles")', function() {
      // uncomment below and update the code to test the property styles
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property idpType (base name: "idpType")', function() {
      // uncomment below and update the code to test the property idpType
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property idpName (base name: "idpName")', function() {
      // uncomment below and update the code to test the property idpName
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property idpId (base name: "idpId")', function() {
      // uncomment below and update the code to test the property idpId
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property idpEnabled (base name: "idpEnabled")', function() {
      // uncomment below and update the code to test the property idpEnabled
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property iconSrc (base name: "iconSrc")', function() {
      // uncomment below and update the code to test the property iconSrc
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new PingOnePlatformApiSsoAndBase.FormFieldSocialLoginButton();
      //expect(instance).to.be();
    });

  });

}));
