/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GatewayTypeLDAPAllOfUserTypes', function() {
    it('should create an instance of GatewayTypeLDAPAllOfUserTypes', function() {
      // uncomment below and update the code to test GatewayTypeLDAPAllOfUserTypes
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes);
    });

    it('should have the property allowPasswordChanges (base name: "allowPasswordChanges")', function() {
      // uncomment below and update the code to test the property allowPasswordChanges
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property updateUserOnSuccessfulAuthentication (base name: "updateUserOnSuccessfulAuthentication")', function() {
      // uncomment below and update the code to test the property updateUserOnSuccessfulAuthentication
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property newUserLookup (base name: "newUserLookup")', function() {
      // uncomment below and update the code to test the property newUserLookup
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property orderedCorrelationAttributes (base name: "orderedCorrelationAttributes")', function() {
      // uncomment below and update the code to test the property orderedCorrelationAttributes
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property passwordAuthority (base name: "passwordAuthority")', function() {
      // uncomment below and update the code to test the property passwordAuthority
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

    it('should have the property searchBaseDn (base name: "searchBaseDn")', function() {
      // uncomment below and update the code to test the property searchBaseDn
      //var instance = new PingOnePlatformApiSsoAndBase.GatewayTypeLDAPAllOfUserTypes();
      //expect(instance).to.be();
    });

  });

}));
