/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PropagationStoreConfigurationSlack', function() {
    it('should create an instance of PropagationStoreConfigurationSlack', function() {
      // uncomment below and update the code to test PropagationStoreConfigurationSlack
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack);
    });

    it('should have the property CREATE_USERS (base name: "CREATE_USERS")', function() {
      // uncomment below and update the code to test the property CREATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property DEPROVISION_USERS (base name: "DEPROVISION_USERS")', function() {
      // uncomment below and update the code to test the property DEPROVISION_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property DISABLE_USERS (base name: "DISABLE_USERS")', function() {
      // uncomment below and update the code to test the property DISABLE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property OAUTH_ACCESS_TOKEN (base name: "OAUTH_ACCESS_TOKEN")', function() {
      // uncomment below and update the code to test the property OAUTH_ACCESS_TOKEN
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property REMOVE_ACTION (base name: "REMOVE_ACTION")', function() {
      // uncomment below and update the code to test the property REMOVE_ACTION
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property UNIQUE_USER_IDENTIFIER (base name: "UNIQUE_USER_IDENTIFIER")', function() {
      // uncomment below and update the code to test the property UNIQUE_USER_IDENTIFIER
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

    it('should have the property UPDATE_USERS (base name: "UPDATE_USERS")', function() {
      // uncomment below and update the code to test the property UPDATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationSlack();
      //expect(instance).to.be();
    });

  });

}));
