/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PropagationStoreConfigurationLDAPGateway', function() {
    it('should create an instance of PropagationStoreConfigurationLDAPGateway', function() {
      // uncomment below and update the code to test PropagationStoreConfigurationLDAPGateway
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway);
    });

    it('should have the property ATTRIBUTE_METADATA (base name: "ATTRIBUTE_METADATA")', function() {
      // uncomment below and update the code to test the property ATTRIBUTE_METADATA
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property CLIENT_ID (base name: "CLIENT_ID")', function() {
      // uncomment below and update the code to test the property CLIENT_ID
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property CLIENT_SECRET (base name: "CLIENT_SECRET")', function() {
      // uncomment below and update the code to test the property CLIENT_SECRET
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property CREATE_USERS (base name: "CREATE_USERS")', function() {
      // uncomment below and update the code to test the property CREATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property DELETE_USERS (base name: "DELETE_USERS")', function() {
      // uncomment below and update the code to test the property DELETE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property ENVIRONMENT_ID (base name: "ENVIRONMENT_ID")', function() {
      // uncomment below and update the code to test the property ENVIRONMENT_ID
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property GATEWAY_BASE_URL (base name: "GATEWAY_BASE_URL")', function() {
      // uncomment below and update the code to test the property GATEWAY_BASE_URL
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property GATEWAY_ID (base name: "GATEWAY_ID")', function() {
      // uncomment below and update the code to test the property GATEWAY_ID
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property LDAP_TYPE (base name: "LDAP_TYPE")', function() {
      // uncomment below and update the code to test the property LDAP_TYPE
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property OAUTH_URL (base name: "OAUTH_URL")', function() {
      // uncomment below and update the code to test the property OAUTH_URL
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

    it('should have the property UPDATE_USERS (base name: "UPDATE_USERS")', function() {
      // uncomment below and update the code to test the property UPDATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationLDAPGateway();
      //expect(instance).to.be();
    });

  });

}));
