/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PropagationStoreConfigurationPingOne', function() {
    it('should create an instance of PropagationStoreConfigurationPingOne', function() {
      // uncomment below and update the code to test PropagationStoreConfigurationPingOne
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be.a(PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne);
    });

    it('should have the property CLIENT_ID (base name: "CLIENT_ID")', function() {
      // uncomment below and update the code to test the property CLIENT_ID
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property CLIENT_SECRET (base name: "CLIENT_SECRET")', function() {
      // uncomment below and update the code to test the property CLIENT_SECRET
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property CREATE_USERS (base name: "CREATE_USERS")', function() {
      // uncomment below and update the code to test the property CREATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property DEFAULT_AUTH_METHOD (base name: "DEFAULT_AUTH_METHOD")', function() {
      // uncomment below and update the code to test the property DEFAULT_AUTH_METHOD
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property DISABLE_USERS (base name: "DISABLE_USERS")', function() {
      // uncomment below and update the code to test the property DISABLE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property ENVIRONMENT_ID (base name: "ENVIRONMENT_ID")', function() {
      // uncomment below and update the code to test the property ENVIRONMENT_ID
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property MFA_USER_DEVICE_MANAGEMENT (base name: "MFA_USER_DEVICE_MANAGEMENT")', function() {
      // uncomment below and update the code to test the property MFA_USER_DEVICE_MANAGEMENT
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property PROVISION_DISABLED_USERS_PROV_OPT (base name: "PROVISION_DISABLED_USERS_PROV_OPT")', function() {
      // uncomment below and update the code to test the property PROVISION_DISABLED_USERS_PROV_OPT
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property REGION (base name: "REGION")', function() {
      // uncomment below and update the code to test the property REGION
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property REMOVE_ACTION (base name: "REMOVE_ACTION")', function() {
      // uncomment below and update the code to test the property REMOVE_ACTION
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

    it('should have the property UPDATE_USERS (base name: "UPDATE_USERS")', function() {
      // uncomment below and update the code to test the property UPDATE_USERS
      //var instance = new PingOnePlatformApiSsoAndBase.PropagationStoreConfigurationPingOne();
      //expect(instance).to.be();
    });

  });

}));
