/**
 * PingOne Platform API - PingOne MFA
 * The PingOne Platform API covering the PingOne MFA service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeviceAuthenticationPolicyFIDODevice model module.
 * @module model/DeviceAuthenticationPolicyFIDODevice
 * @version 2023-06-29
 */
class DeviceAuthenticationPolicyFIDODevice {
    /**
     * Constructs a new <code>DeviceAuthenticationPolicyFIDODevice</code>.
     * @alias module:model/DeviceAuthenticationPolicyFIDODevice
     * @param enabled {Boolean} Enabled or disabled in the policy.
     */
    constructor(enabled) { 
        
        DeviceAuthenticationPolicyFIDODevice.initialize(this, enabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled) { 
        obj['enabled'] = enabled;
    }

    /**
     * Constructs a <code>DeviceAuthenticationPolicyFIDODevice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceAuthenticationPolicyFIDODevice} obj Optional instance to populate.
     * @return {module:model/DeviceAuthenticationPolicyFIDODevice} The populated <code>DeviceAuthenticationPolicyFIDODevice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceAuthenticationPolicyFIDODevice();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('pairingDisabled')) {
                obj['pairingDisabled'] = ApiClient.convertToType(data['pairingDisabled'], 'Boolean');
            }
            if (data.hasOwnProperty('fidoPolicyId')) {
                obj['fidoPolicyId'] = ApiClient.convertToType(data['fidoPolicyId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeviceAuthenticationPolicyFIDODevice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeviceAuthenticationPolicyFIDODevice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeviceAuthenticationPolicyFIDODevice.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fidoPolicyId'] && !(typeof data['fidoPolicyId'] === 'string' || data['fidoPolicyId'] instanceof String)) {
            throw new Error("Expected the field `fidoPolicyId` to be a primitive type in the JSON string but got " + data['fidoPolicyId']);
        }

        return true;
    }


}

DeviceAuthenticationPolicyFIDODevice.RequiredProperties = ["enabled"];

/**
 * Enabled or disabled in the policy.
 * @member {Boolean} enabled
 */
DeviceAuthenticationPolicyFIDODevice.prototype['enabled'] = undefined;

/**
 * You can set `pairingDisabled` to true to prevent users from pairing new devices with the relevant method. You can use this option if you want to phase out an existing authentication method but want to allow users to continue using the method for authentication for existing devices.
 * @member {Boolean} pairingDisabled
 */
DeviceAuthenticationPolicyFIDODevice.prototype['pairingDisabled'] = undefined;

/**
 * Specifies the FIDO policy UUID. This property can be null. When null, the environment's default FIDO Policy is used.
 * @member {String} fidoPolicyId
 */
DeviceAuthenticationPolicyFIDODevice.prototype['fidoPolicyId'] = undefined;






export default DeviceAuthenticationPolicyFIDODevice;

