/**
 * PingOne Platform API - PingOne MFA
 * The PingOne Platform API covering the PingOne MFA service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeviceAuthenticationPolicyMobileOtpWindowStepSize from './DeviceAuthenticationPolicyMobileOtpWindowStepSize';

/**
 * The DeviceAuthenticationPolicyMobileOtpWindow model module.
 * @module model/DeviceAuthenticationPolicyMobileOtpWindow
 * @version 2023-06-29
 */
class DeviceAuthenticationPolicyMobileOtpWindow {
    /**
     * Constructs a new <code>DeviceAuthenticationPolicyMobileOtpWindow</code>.
     * @alias module:model/DeviceAuthenticationPolicyMobileOtpWindow
     * @param stepSize {module:model/DeviceAuthenticationPolicyMobileOtpWindowStepSize} 
     */
    constructor(stepSize) { 
        
        DeviceAuthenticationPolicyMobileOtpWindow.initialize(this, stepSize);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, stepSize) { 
        obj['stepSize'] = stepSize;
    }

    /**
     * Constructs a <code>DeviceAuthenticationPolicyMobileOtpWindow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceAuthenticationPolicyMobileOtpWindow} obj Optional instance to populate.
     * @return {module:model/DeviceAuthenticationPolicyMobileOtpWindow} The populated <code>DeviceAuthenticationPolicyMobileOtpWindow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceAuthenticationPolicyMobileOtpWindow();

            if (data.hasOwnProperty('stepSize')) {
                obj['stepSize'] = DeviceAuthenticationPolicyMobileOtpWindowStepSize.constructFromObject(data['stepSize']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeviceAuthenticationPolicyMobileOtpWindow</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeviceAuthenticationPolicyMobileOtpWindow</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeviceAuthenticationPolicyMobileOtpWindow.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `stepSize`
        if (data['stepSize']) { // data not null
          DeviceAuthenticationPolicyMobileOtpWindowStepSize.validateJSON(data['stepSize']);
        }

        return true;
    }


}

DeviceAuthenticationPolicyMobileOtpWindow.RequiredProperties = ["stepSize"];

/**
 * @member {module:model/DeviceAuthenticationPolicyMobileOtpWindowStepSize} stepSize
 */
DeviceAuthenticationPolicyMobileOtpWindow.prototype['stepSize'] = undefined;






export default DeviceAuthenticationPolicyMobileOtpWindow;

