/**
 * PingOne Platform API - PingOne MFA
 * The PingOne Platform API covering the PingOne MFA service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnumMFASettingsPairingKeyFormat from './EnumMFASettingsPairingKeyFormat';

/**
 * The MFASettingsPairing model module.
 * @module model/MFASettingsPairing
 * @version 2023-06-29
 */
class MFASettingsPairing {
    /**
     * Constructs a new <code>MFASettingsPairing</code>.
     * An object that contains pairing settings.
     * @alias module:model/MFASettingsPairing
     * @param maxAllowedDevices {Number} An integer that defines the maximum number of MFA devices each user can have. This can be any number up to 15. The default value is 5.
     * @param pairingKeyFormat {module:model/EnumMFASettingsPairingKeyFormat} 
     */
    constructor(maxAllowedDevices, pairingKeyFormat) { 
        
        MFASettingsPairing.initialize(this, maxAllowedDevices, pairingKeyFormat);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, maxAllowedDevices, pairingKeyFormat) { 
        obj['maxAllowedDevices'] = maxAllowedDevices || 5;
        obj['pairingKeyFormat'] = pairingKeyFormat;
    }

    /**
     * Constructs a <code>MFASettingsPairing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MFASettingsPairing} obj Optional instance to populate.
     * @return {module:model/MFASettingsPairing} The populated <code>MFASettingsPairing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MFASettingsPairing();

            if (data.hasOwnProperty('maxAllowedDevices')) {
                obj['maxAllowedDevices'] = ApiClient.convertToType(data['maxAllowedDevices'], 'Number');
            }
            if (data.hasOwnProperty('pairingKeyFormat')) {
                obj['pairingKeyFormat'] = EnumMFASettingsPairingKeyFormat.constructFromObject(data['pairingKeyFormat']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MFASettingsPairing</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MFASettingsPairing</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MFASettingsPairing.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MFASettingsPairing.RequiredProperties = ["maxAllowedDevices", "pairingKeyFormat"];

/**
 * An integer that defines the maximum number of MFA devices each user can have. This can be any number up to 15. The default value is 5.
 * @member {Number} maxAllowedDevices
 * @default 5
 */
MFASettingsPairing.prototype['maxAllowedDevices'] = 5;

/**
 * @member {module:model/EnumMFASettingsPairingKeyFormat} pairingKeyFormat
 */
MFASettingsPairing.prototype['pairingKeyFormat'] = undefined;






export default MFASettingsPairing;

