/**
 * PingOne Platform API - Credentials
 * The PingOne Platform API covering the PingOne Credentials service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiCredentials);
  }
}(this, function(expect, PingOnePlatformApiCredentials) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CredentialIssuerProfile', function() {
    it('should create an instance of CredentialIssuerProfile', function() {
      // uncomment below and update the code to test CredentialIssuerProfile
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be.a(PingOnePlatformApiCredentials.CredentialIssuerProfile);
    });

    it('should have the property links (base name: "_links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property applicationInstance (base name: "applicationInstance")', function() {
      // uncomment below and update the code to test the property applicationInstance
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property environment (base name: "environment")', function() {
      // uncomment below and update the code to test the property environment
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property siteUrl (base name: "siteUrl")', function() {
      // uncomment below and update the code to test the property siteUrl
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

    it('should have the property customEmailTemplate (base name: "customEmailTemplate")', function() {
      // uncomment below and update the code to test the property customEmailTemplate
      //var instance = new PingOnePlatformApiCredentials.CredentialIssuerProfile();
      //expect(instance).to.be();
    });

  });

}));
