/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EnumBrandingLogoType.
* @enum {}
* @readonly
*/
export default class EnumBrandingLogoType {
    
        /**
         * value: "IMAGE"
         * @const
         */
        "IMAGE" = "IMAGE";

    
        /**
         * value: "NONE"
         * @const
         */
        "NONE" = "NONE";

    

    /**
    * Returns a <code>EnumBrandingLogoType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EnumBrandingLogoType} The enum <code>EnumBrandingLogoType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

