/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LicenseCredentials model module.
 * @module model/LicenseCredentials
 * @version 2023-06-29
 */
class LicenseCredentials {
    /**
     * Constructs a new <code>LicenseCredentials</code>.
     * @alias module:model/LicenseCredentials
     */
    constructor() { 
        
        LicenseCredentials.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LicenseCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LicenseCredentials} obj Optional instance to populate.
     * @return {module:model/LicenseCredentials} The populated <code>LicenseCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LicenseCredentials();

            if (data.hasOwnProperty('allowCredentials')) {
                obj['allowCredentials'] = ApiClient.convertToType(data['allowCredentials'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LicenseCredentials</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LicenseCredentials</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} allowCredentials
 */
LicenseCredentials.prototype['allowCredentials'] = undefined;






export default LicenseCredentials;

