/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnumPropagationStoreTypeRemoveActionDisableDelete from './EnumPropagationStoreTypeRemoveActionDisableDelete';

/**
 * The PropagationStoreConfigurationGoogleApps model module.
 * @module model/PropagationStoreConfigurationGoogleApps
 * @version 2023-06-29
 */
class PropagationStoreConfigurationGoogleApps {
    /**
     * Constructs a new <code>PropagationStoreConfigurationGoogleApps</code>.
     * @alias module:model/PropagationStoreConfigurationGoogleApps
     * @param APPLICATION_NAME {String} Name of the application using the store.
     * @param DOMAIN {String} The account's domain name.
     * @param OAUTH_ACCESS_TOKEN {String} OAuth 2 access token.
     * @param OAUTH_CLIENT_ID {String} GoogleApps identifier of the client associated with the propagation store.
     * @param OAUTH_CLIENT_SECRET {String} GoogleApps secret of the client associated with the propagation store.
     * @param OAUTH_REFRESH_TOKEN {String} OAuth 2 refresh token.
     */
    constructor(APPLICATION_NAME, DOMAIN, OAUTH_ACCESS_TOKEN, OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OAUTH_REFRESH_TOKEN) { 
        
        PropagationStoreConfigurationGoogleApps.initialize(this, APPLICATION_NAME, DOMAIN, OAUTH_ACCESS_TOKEN, OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OAUTH_REFRESH_TOKEN);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, APPLICATION_NAME, DOMAIN, OAUTH_ACCESS_TOKEN, OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OAUTH_REFRESH_TOKEN) { 
        obj['APPLICATION_NAME'] = APPLICATION_NAME;
        obj['DOMAIN'] = DOMAIN;
        obj['OAUTH_ACCESS_TOKEN'] = OAUTH_ACCESS_TOKEN;
        obj['OAUTH_CLIENT_ID'] = OAUTH_CLIENT_ID;
        obj['OAUTH_CLIENT_SECRET'] = OAUTH_CLIENT_SECRET;
        obj['OAUTH_REFRESH_TOKEN'] = OAUTH_REFRESH_TOKEN;
    }

    /**
     * Constructs a <code>PropagationStoreConfigurationGoogleApps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropagationStoreConfigurationGoogleApps} obj Optional instance to populate.
     * @return {module:model/PropagationStoreConfigurationGoogleApps} The populated <code>PropagationStoreConfigurationGoogleApps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropagationStoreConfigurationGoogleApps();

            if (data.hasOwnProperty('APPLICATION_NAME')) {
                obj['APPLICATION_NAME'] = ApiClient.convertToType(data['APPLICATION_NAME'], 'String');
            }
            if (data.hasOwnProperty('CREATE_USERS')) {
                obj['CREATE_USERS'] = ApiClient.convertToType(data['CREATE_USERS'], 'Boolean');
            }
            if (data.hasOwnProperty('DEPROVISION_USERS')) {
                obj['DEPROVISION_USERS'] = ApiClient.convertToType(data['DEPROVISION_USERS'], 'Boolean');
            }
            if (data.hasOwnProperty('DISABLE_USERS')) {
                obj['DISABLE_USERS'] = ApiClient.convertToType(data['DISABLE_USERS'], 'Boolean');
            }
            if (data.hasOwnProperty('DOMAIN')) {
                obj['DOMAIN'] = ApiClient.convertToType(data['DOMAIN'], 'String');
            }
            if (data.hasOwnProperty('OAUTH_ACCESS_TOKEN')) {
                obj['OAUTH_ACCESS_TOKEN'] = ApiClient.convertToType(data['OAUTH_ACCESS_TOKEN'], 'String');
            }
            if (data.hasOwnProperty('OAUTH_CLIENT_ID')) {
                obj['OAUTH_CLIENT_ID'] = ApiClient.convertToType(data['OAUTH_CLIENT_ID'], 'String');
            }
            if (data.hasOwnProperty('OAUTH_CLIENT_SECRET')) {
                obj['OAUTH_CLIENT_SECRET'] = ApiClient.convertToType(data['OAUTH_CLIENT_SECRET'], 'String');
            }
            if (data.hasOwnProperty('OAUTH_REFRESH_TOKEN')) {
                obj['OAUTH_REFRESH_TOKEN'] = ApiClient.convertToType(data['OAUTH_REFRESH_TOKEN'], 'String');
            }
            if (data.hasOwnProperty('PROVISION_DISABLED_USERS_PROV_OPT')) {
                obj['PROVISION_DISABLED_USERS_PROV_OPT'] = ApiClient.convertToType(data['PROVISION_DISABLED_USERS_PROV_OPT'], 'Boolean');
            }
            if (data.hasOwnProperty('REMOVE_ACTION')) {
                obj['REMOVE_ACTION'] = EnumPropagationStoreTypeRemoveActionDisableDelete.constructFromObject(data['REMOVE_ACTION']);
            }
            if (data.hasOwnProperty('UPDATE_USERS')) {
                obj['UPDATE_USERS'] = ApiClient.convertToType(data['UPDATE_USERS'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PropagationStoreConfigurationGoogleApps</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PropagationStoreConfigurationGoogleApps</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PropagationStoreConfigurationGoogleApps.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['APPLICATION_NAME'] && !(typeof data['APPLICATION_NAME'] === 'string' || data['APPLICATION_NAME'] instanceof String)) {
            throw new Error("Expected the field `APPLICATION_NAME` to be a primitive type in the JSON string but got " + data['APPLICATION_NAME']);
        }
        // ensure the json data is a string
        if (data['DOMAIN'] && !(typeof data['DOMAIN'] === 'string' || data['DOMAIN'] instanceof String)) {
            throw new Error("Expected the field `DOMAIN` to be a primitive type in the JSON string but got " + data['DOMAIN']);
        }
        // ensure the json data is a string
        if (data['OAUTH_ACCESS_TOKEN'] && !(typeof data['OAUTH_ACCESS_TOKEN'] === 'string' || data['OAUTH_ACCESS_TOKEN'] instanceof String)) {
            throw new Error("Expected the field `OAUTH_ACCESS_TOKEN` to be a primitive type in the JSON string but got " + data['OAUTH_ACCESS_TOKEN']);
        }
        // ensure the json data is a string
        if (data['OAUTH_CLIENT_ID'] && !(typeof data['OAUTH_CLIENT_ID'] === 'string' || data['OAUTH_CLIENT_ID'] instanceof String)) {
            throw new Error("Expected the field `OAUTH_CLIENT_ID` to be a primitive type in the JSON string but got " + data['OAUTH_CLIENT_ID']);
        }
        // ensure the json data is a string
        if (data['OAUTH_CLIENT_SECRET'] && !(typeof data['OAUTH_CLIENT_SECRET'] === 'string' || data['OAUTH_CLIENT_SECRET'] instanceof String)) {
            throw new Error("Expected the field `OAUTH_CLIENT_SECRET` to be a primitive type in the JSON string but got " + data['OAUTH_CLIENT_SECRET']);
        }
        // ensure the json data is a string
        if (data['OAUTH_REFRESH_TOKEN'] && !(typeof data['OAUTH_REFRESH_TOKEN'] === 'string' || data['OAUTH_REFRESH_TOKEN'] instanceof String)) {
            throw new Error("Expected the field `OAUTH_REFRESH_TOKEN` to be a primitive type in the JSON string but got " + data['OAUTH_REFRESH_TOKEN']);
        }

        return true;
    }


}

PropagationStoreConfigurationGoogleApps.RequiredProperties = ["APPLICATION_NAME", "DOMAIN", "OAUTH_ACCESS_TOKEN", "OAUTH_CLIENT_ID", "OAUTH_CLIENT_SECRET", "OAUTH_REFRESH_TOKEN"];

/**
 * Name of the application using the store.
 * @member {String} APPLICATION_NAME
 */
PropagationStoreConfigurationGoogleApps.prototype['APPLICATION_NAME'] = undefined;

/**
 * Whether or not users are allowed to be created.
 * @member {Boolean} CREATE_USERS
 */
PropagationStoreConfigurationGoogleApps.prototype['CREATE_USERS'] = undefined;

/**
 * Whether or not users are allowed to be deprovisioned (removed) following action specified in `REMOVE_ACTION`.
 * @member {Boolean} DEPROVISION_USERS
 */
PropagationStoreConfigurationGoogleApps.prototype['DEPROVISION_USERS'] = undefined;

/**
 * Whether or not users are allowed to be disabled.
 * @member {Boolean} DISABLE_USERS
 */
PropagationStoreConfigurationGoogleApps.prototype['DISABLE_USERS'] = undefined;

/**
 * The account's domain name.
 * @member {String} DOMAIN
 */
PropagationStoreConfigurationGoogleApps.prototype['DOMAIN'] = undefined;

/**
 * OAuth 2 access token.
 * @member {String} OAUTH_ACCESS_TOKEN
 */
PropagationStoreConfigurationGoogleApps.prototype['OAUTH_ACCESS_TOKEN'] = undefined;

/**
 * GoogleApps identifier of the client associated with the propagation store.
 * @member {String} OAUTH_CLIENT_ID
 */
PropagationStoreConfigurationGoogleApps.prototype['OAUTH_CLIENT_ID'] = undefined;

/**
 * GoogleApps secret of the client associated with the propagation store.
 * @member {String} OAUTH_CLIENT_SECRET
 */
PropagationStoreConfigurationGoogleApps.prototype['OAUTH_CLIENT_SECRET'] = undefined;

/**
 * OAuth 2 refresh token.
 * @member {String} OAUTH_REFRESH_TOKEN
 */
PropagationStoreConfigurationGoogleApps.prototype['OAUTH_REFRESH_TOKEN'] = undefined;

/**
 * Whether or not disabled users can be provisioned. Defaults to `true` and, if used, must be set to `true`.
 * @member {Boolean} PROVISION_DISABLED_USERS_PROV_OPT
 * @default true
 */
PropagationStoreConfigurationGoogleApps.prototype['PROVISION_DISABLED_USERS_PROV_OPT'] = true;

/**
 * @member {module:model/EnumPropagationStoreTypeRemoveActionDisableDelete} REMOVE_ACTION
 */
PropagationStoreConfigurationGoogleApps.prototype['REMOVE_ACTION'] = undefined;

/**
 * Whether or not users are allowed to be updated.
 * @member {Boolean} UPDATE_USERS
 */
PropagationStoreConfigurationGoogleApps.prototype['UPDATE_USERS'] = undefined;






export default PropagationStoreConfigurationGoogleApps;

