/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignOnPolicyActionCommonConditionGeovelocityValid model module.
 * @module model/SignOnPolicyActionCommonConditionGeovelocityValid
 * @version 2023-06-29
 */
class SignOnPolicyActionCommonConditionGeovelocityValid {
    /**
     * Constructs a new <code>SignOnPolicyActionCommonConditionGeovelocityValid</code>.
     * @alias module:model/SignOnPolicyActionCommonConditionGeovelocityValid
     * @param previousSuccessfulAuthenticationIp {String} 
     * @param previousSuccessfulAuthenticationTime {String} 
     */
    constructor(previousSuccessfulAuthenticationIp, previousSuccessfulAuthenticationTime) { 
        
        SignOnPolicyActionCommonConditionGeovelocityValid.initialize(this, previousSuccessfulAuthenticationIp, previousSuccessfulAuthenticationTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, previousSuccessfulAuthenticationIp, previousSuccessfulAuthenticationTime) { 
        obj['previousSuccessfulAuthenticationIp'] = previousSuccessfulAuthenticationIp;
        obj['previousSuccessfulAuthenticationTime'] = previousSuccessfulAuthenticationTime;
    }

    /**
     * Constructs a <code>SignOnPolicyActionCommonConditionGeovelocityValid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignOnPolicyActionCommonConditionGeovelocityValid} obj Optional instance to populate.
     * @return {module:model/SignOnPolicyActionCommonConditionGeovelocityValid} The populated <code>SignOnPolicyActionCommonConditionGeovelocityValid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignOnPolicyActionCommonConditionGeovelocityValid();

            if (data.hasOwnProperty('previousSuccessfulAuthenticationIp')) {
                obj['previousSuccessfulAuthenticationIp'] = ApiClient.convertToType(data['previousSuccessfulAuthenticationIp'], 'String');
            }
            if (data.hasOwnProperty('previousSuccessfulAuthenticationTime')) {
                obj['previousSuccessfulAuthenticationTime'] = ApiClient.convertToType(data['previousSuccessfulAuthenticationTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignOnPolicyActionCommonConditionGeovelocityValid</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignOnPolicyActionCommonConditionGeovelocityValid</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignOnPolicyActionCommonConditionGeovelocityValid.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['previousSuccessfulAuthenticationIp'] && !(typeof data['previousSuccessfulAuthenticationIp'] === 'string' || data['previousSuccessfulAuthenticationIp'] instanceof String)) {
            throw new Error("Expected the field `previousSuccessfulAuthenticationIp` to be a primitive type in the JSON string but got " + data['previousSuccessfulAuthenticationIp']);
        }
        // ensure the json data is a string
        if (data['previousSuccessfulAuthenticationTime'] && !(typeof data['previousSuccessfulAuthenticationTime'] === 'string' || data['previousSuccessfulAuthenticationTime'] instanceof String)) {
            throw new Error("Expected the field `previousSuccessfulAuthenticationTime` to be a primitive type in the JSON string but got " + data['previousSuccessfulAuthenticationTime']);
        }

        return true;
    }


}

SignOnPolicyActionCommonConditionGeovelocityValid.RequiredProperties = ["previousSuccessfulAuthenticationIp", "previousSuccessfulAuthenticationTime"];

/**
 * @member {String} previousSuccessfulAuthenticationIp
 */
SignOnPolicyActionCommonConditionGeovelocityValid.prototype['previousSuccessfulAuthenticationIp'] = undefined;

/**
 * @member {String} previousSuccessfulAuthenticationTime
 */
SignOnPolicyActionCommonConditionGeovelocityValid.prototype['previousSuccessfulAuthenticationTime'] = undefined;






export default SignOnPolicyActionCommonConditionGeovelocityValid;

