/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode model module.
 * @module model/SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode
 * @version 2023-06-29
 */
class SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode {
    /**
     * Constructs a new <code>SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode</code>.
     * @alias module:model/SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode
     * @param enabled {Boolean} Select this option to allow users to log in when PingOne and or PingID are not available.
     */
    constructor(enabled) { 
        
        SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode.initialize(this, enabled);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled) { 
        obj['enabled'] = enabled;
    }

    /**
     * Constructs a <code>SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode} obj Optional instance to populate.
     * @return {module:model/SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode} The populated <code>SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode.RequiredProperties = ["enabled"];

/**
 * Select this option to allow users to log in when PingOne and or PingID are not available.
 * @member {Boolean} enabled
 */
SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode.prototype['enabled'] = undefined;






export default SignOnPolicyActionPingIDWinLoginPasswordlessAllOfOfflineMode;

