/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserLastSignOn model module.
 * @module model/UserLastSignOn
 * @version 2023-06-29
 */
class UserLastSignOn {
    /**
     * Constructs a new <code>UserLastSignOn</code>.
     * @alias module:model/UserLastSignOn
     */
    constructor() { 
        
        UserLastSignOn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserLastSignOn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserLastSignOn} obj Optional instance to populate.
     * @return {module:model/UserLastSignOn} The populated <code>UserLastSignOn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLastSignOn();

            if (data.hasOwnProperty('at')) {
                obj['at'] = ApiClient.convertToType(data['at'], 'Date');
            }
            if (data.hasOwnProperty('remoteIp')) {
                obj['remoteIp'] = ApiClient.convertToType(data['remoteIp'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserLastSignOn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserLastSignOn</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['remoteIp'] && !(typeof data['remoteIp'] === 'string' || data['remoteIp'] instanceof String)) {
            throw new Error("Expected the field `remoteIp` to be a primitive type in the JSON string but got " + data['remoteIp']);
        }

        return true;
    }


}



/**
 * The time of the last successful login of the user through the PingOne flow API.
 * @member {Date} at
 */
UserLastSignOn.prototype['at'] = undefined;

/**
 * The IP address of the last successful login of the user through the PingOne flow API.
 * @member {String} remoteIp
 */
UserLastSignOn.prototype['remoteIp'] = undefined;






export default UserLastSignOn;

