/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnumUserLifecycleStatus from './EnumUserLifecycleStatus';

/**
 * The UserLifecycle model module.
 * @module model/UserLifecycle
 * @version 2023-06-29
 */
class UserLifecycle {
    /**
     * Constructs a new <code>UserLifecycle</code>.
     * @alias module:model/UserLifecycle
     */
    constructor() { 
        
        UserLifecycle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserLifecycle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserLifecycle} obj Optional instance to populate.
     * @return {module:model/UserLifecycle} The populated <code>UserLifecycle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLifecycle();

            if (data.hasOwnProperty('status')) {
                obj['status'] = EnumUserLifecycleStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('suppressVerificationCode')) {
                obj['suppressVerificationCode'] = ApiClient.convertToType(data['suppressVerificationCode'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserLifecycle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserLifecycle</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/EnumUserLifecycleStatus} status
 */
UserLifecycle.prototype['status'] = undefined;

/**
 * Used when importing a user and the lifecycle.status is set to VERIFICATION_REQUIRED. If this property is set to true, no verification email is sent to the user. If this property is omitted or set to false, a verification email is sent automatically to the user.
 * @member {Boolean} suppressVerificationCode
 */
UserLifecycle.prototype['suppressVerificationCode'] = undefined;






export default UserLifecycle;

