/**
 * PingOne Platform API - SSO and Base
 * The PingOne Platform API covering the base and SSO services (otherwise known as the Management APIs)
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PingOnePlatformApiSsoAndBase);
  }
}(this, function(expect, PingOnePlatformApiSsoAndBase) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PingOnePlatformApiSsoAndBase.KeyRotationPoliciesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KeyRotationPoliciesApi', function() {
    describe('createKeyRotationPolicy', function() {
      it('should call createKeyRotationPolicy successfully', function(done) {
        //uncomment below and update the code to test createKeyRotationPolicy
        //instance.createKeyRotationPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteKeyRotationPolicy', function() {
      it('should call deleteKeyRotationPolicy successfully', function(done) {
        //uncomment below and update the code to test deleteKeyRotationPolicy
        //instance.deleteKeyRotationPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKeyRotationPolicies', function() {
      it('should call getKeyRotationPolicies successfully', function(done) {
        //uncomment below and update the code to test getKeyRotationPolicies
        //instance.getKeyRotationPolicies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKeyRotationPolicy', function() {
      it('should call getKeyRotationPolicy successfully', function(done) {
        //uncomment below and update the code to test getKeyRotationPolicy
        //instance.getKeyRotationPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateKeyRotationPolicy', function() {
      it('should call updateKeyRotationPolicy successfully', function(done) {
        //uncomment below and update the code to test updateKeyRotationPolicy
        //instance.updateKeyRotationPolicy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
