/**
 * PingOne Platform API - PingOne Risk
 * The PingOne Platform API covering the PingOne Risk service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EnumRiskLevel.
* @enum {}
* @readonly
*/
export default class EnumRiskLevel {
    
        /**
         * value: "LOW"
         * @const
         */
        "LOW" = "LOW";

    
        /**
         * value: "MEDIUM"
         * @const
         */
        "MEDIUM" = "MEDIUM";

    
        /**
         * value: "HIGH"
         * @const
         */
        "HIGH" = "HIGH";

    

    /**
    * Returns a <code>EnumRiskLevel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EnumRiskLevel} The enum <code>EnumRiskLevel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

