/**
 * PingOne Platform API - PingOne Risk
 * The PingOne Platform API covering the PingOne Risk service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EnumPredictorVelocityMeasure.
* @enum {}
* @readonly
*/
export default class EnumPredictorVelocityMeasure {
    
        /**
         * value: "DISTINCT_COUNT"
         * @const
         */
        "DISTINCT_COUNT" = "DISTINCT_COUNT";

    

    /**
    * Returns a <code>EnumPredictorVelocityMeasure</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EnumPredictorVelocityMeasure} The enum <code>EnumPredictorVelocityMeasure</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

