/**
 * PingOne Platform API - PingOne Risk
 * The PingOne Platform API covering the PingOne Risk service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EnumThresholdSource.
* @enum {}
* @readonly
*/
export default class EnumThresholdSource {
    
        /**
         * value: "MIN_NOT_REACHED"
         * @const
         */
        "MIN_NOT_REACHED" = "MIN_NOT_REACHED";

    
        /**
         * value: "CALCULATED"
         * @const
         */
        "CALCULATED" = "CALCULATED";

    
        /**
         * value: "ENVIRONMENT_FALLBACK"
         * @const
         */
        "ENVIRONMENT_FALLBACK" = "ENVIRONMENT_FALLBACK";

    
        /**
         * value: "DEFAULT_FALLBACK"
         * @const
         */
        "DEFAULT_FALLBACK" = "DEFAULT_FALLBACK";

    

    /**
    * Returns a <code>EnumThresholdSource</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EnumThresholdSource} The enum <code>EnumThresholdSource</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

