/**
 * PingOne Platform API - PingOne Risk
 * The PingOne Platform API covering the PingOne Risk service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnumPredictorVelocityUseType from './EnumPredictorVelocityUseType';

/**
 * The RiskPredictorVelocityAllOfUse model module.
 * @module model/RiskPredictorVelocityAllOfUse
 * @version 2023-06-29
 */
class RiskPredictorVelocityAllOfUse {
    /**
     * Constructs a new <code>RiskPredictorVelocityAllOfUse</code>.
     * @alias module:model/RiskPredictorVelocityAllOfUse
     */
    constructor() { 
        
        RiskPredictorVelocityAllOfUse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RiskPredictorVelocityAllOfUse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RiskPredictorVelocityAllOfUse} obj Optional instance to populate.
     * @return {module:model/RiskPredictorVelocityAllOfUse} The populated <code>RiskPredictorVelocityAllOfUse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RiskPredictorVelocityAllOfUse();

            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('medium')) {
                obj['medium'] = ApiClient.convertToType(data['medium'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = EnumPredictorVelocityUseType.constructFromObject(data['type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RiskPredictorVelocityAllOfUse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RiskPredictorVelocityAllOfUse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} high
 */
RiskPredictorVelocityAllOfUse.prototype['high'] = undefined;

/**
 * @member {Number} medium
 */
RiskPredictorVelocityAllOfUse.prototype['medium'] = undefined;

/**
 * @member {module:model/EnumPredictorVelocityUseType} type
 */
RiskPredictorVelocityAllOfUse.prototype['type'] = undefined;






export default RiskPredictorVelocityAllOfUse;

