OWNER=patrickcping
REPO=pingone-js-sdk
MODULE=agreementmanagement

generate:
	@echo "==> Running generate for $(MODULE)..."
	@./../scripts/generate-module.sh $(OWNER) $(REPO) $(MODULE)

.PHONY: generate