/**
 * PingOne Platform API - Credentials
 * The PingOne Platform API covering the PingOne Credentials service
 *
 * The version of the OpenAPI document: 2023-06-29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CredentialIssuanceRuleUsageInner from './CredentialIssuanceRuleUsageInner';

/**
 * The CredentialIssuanceRuleUsageDetails model module.
 * @module model/CredentialIssuanceRuleUsageDetails
 * @version 2023-06-29
 */
class CredentialIssuanceRuleUsageDetails {
    /**
     * Constructs a new <code>CredentialIssuanceRuleUsageDetails</code>.
     * @alias module:model/CredentialIssuanceRuleUsageDetails
     */
    constructor() { 
        
        CredentialIssuanceRuleUsageDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CredentialIssuanceRuleUsageDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CredentialIssuanceRuleUsageDetails} obj Optional instance to populate.
     * @return {module:model/CredentialIssuanceRuleUsageDetails} The populated <code>CredentialIssuanceRuleUsageDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CredentialIssuanceRuleUsageDetails();

            if (data.hasOwnProperty('issued')) {
                obj['issued'] = ApiClient.convertToType(data['issued'], [CredentialIssuanceRuleUsageInner]);
            }
            if (data.hasOwnProperty('revoked')) {
                obj['revoked'] = ApiClient.convertToType(data['revoked'], [CredentialIssuanceRuleUsageInner]);
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], [CredentialIssuanceRuleUsageInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CredentialIssuanceRuleUsageDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CredentialIssuanceRuleUsageDetails</code>.
     */
    static validateJSON(data) {
        if (data['issued']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['issued'])) {
                throw new Error("Expected the field `issued` to be an array in the JSON data but got " + data['issued']);
            }
            // validate the optional field `issued` (array)
            for (const item of data['issued']) {
                CredentialIssuanceRuleUsageInner.validateJSON(item);
            };
        }
        if (data['revoked']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['revoked'])) {
                throw new Error("Expected the field `revoked` to be an array in the JSON data but got " + data['revoked']);
            }
            // validate the optional field `revoked` (array)
            for (const item of data['revoked']) {
                CredentialIssuanceRuleUsageInner.validateJSON(item);
            };
        }
        if (data['updated']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['updated'])) {
                throw new Error("Expected the field `updated` to be an array in the JSON data but got " + data['updated']);
            }
            // validate the optional field `updated` (array)
            for (const item of data['updated']) {
                CredentialIssuanceRuleUsageInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/CredentialIssuanceRuleUsageInner>} issued
 */
CredentialIssuanceRuleUsageDetails.prototype['issued'] = undefined;

/**
 * @member {Array.<module:model/CredentialIssuanceRuleUsageInner>} revoked
 */
CredentialIssuanceRuleUsageDetails.prototype['revoked'] = undefined;

/**
 * @member {Array.<module:model/CredentialIssuanceRuleUsageInner>} updated
 */
CredentialIssuanceRuleUsageDetails.prototype['updated'] = undefined;






export default CredentialIssuanceRuleUsageDetails;

